/**
 * sms-client
 * API for sms-send functions
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The SmsSendRequest model module.
 * @module com.nvt.api.client/com.nvt.api.client.model/SmsSendRequest
 * @version 1.0.0
 */
class SmsSendRequest {
    /**
     * Constructs a new <code>SmsSendRequest</code>.
     * The structure to describe a request to send a text message.
     * @alias module:com.nvt.api.client/com.nvt.api.client.model/SmsSendRequest
     * @param senderName {String} 
     * @param body {String} 
     * @param phone {String} 
     * @param source {String} 
     */
    constructor(senderName, body, phone, source) { 
        
        SmsSendRequest.initialize(this, senderName, body, phone, source);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, senderName, body, phone, source) { 
        obj['senderName'] = senderName;
        obj['body'] = body;
        obj['phone'] = phone;
        obj['source'] = source;
    }

    /**
     * Constructs a <code>SmsSendRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:com.nvt.api.client/com.nvt.api.client.model/SmsSendRequest} obj Optional instance to populate.
     * @return {module:com.nvt.api.client/com.nvt.api.client.model/SmsSendRequest} The populated <code>SmsSendRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SmsSendRequest();

            if (data.hasOwnProperty('senderName')) {
                obj['senderName'] = ApiClient.convertToType(data['senderName'], 'String');
            }
            if (data.hasOwnProperty('body')) {
                obj['body'] = ApiClient.convertToType(data['body'], 'String');
            }
            if (data.hasOwnProperty('phone')) {
                obj['phone'] = ApiClient.convertToType(data['phone'], 'String');
            }
            if (data.hasOwnProperty('source')) {
                obj['source'] = ApiClient.convertToType(data['source'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} senderName
 */
SmsSendRequest.prototype['senderName'] = undefined;

/**
 * @member {String} body
 */
SmsSendRequest.prototype['body'] = undefined;

/**
 * @member {String} phone
 */
SmsSendRequest.prototype['phone'] = undefined;

/**
 * @member {String} source
 */
SmsSendRequest.prototype['source'] = undefined;






export default SmsSendRequest;

