/**
 * sms-client
 * API for sms-send functions
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The SmsSendResponse model module.
 * @module com.nvt.api.client/com.nvt.api.client.model/SmsSendResponse
 * @version 1.0.0
 */
class SmsSendResponse {
    /**
     * Constructs a new <code>SmsSendResponse</code>.
     * The structure to describe a response to a text message send request.
     * @alias module:com.nvt.api.client/com.nvt.api.client.model/SmsSendResponse
     */
    constructor() { 
        
        SmsSendResponse.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>SmsSendResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:com.nvt.api.client/com.nvt.api.client.model/SmsSendResponse} obj Optional instance to populate.
     * @return {module:com.nvt.api.client/com.nvt.api.client.model/SmsSendResponse} The populated <code>SmsSendResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SmsSendResponse();

            if (data.hasOwnProperty('success')) {
                obj['success'] = ApiClient.convertToType(data['success'], 'Boolean');
            }
            if (data.hasOwnProperty('errorMessage')) {
                obj['errorMessage'] = ApiClient.convertToType(data['errorMessage'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {Boolean} success
 */
SmsSendResponse.prototype['success'] = undefined;

/**
 * @member {String} errorMessage
 */
SmsSendResponse.prototype['errorMessage'] = undefined;






export default SmsSendResponse;

