/**
 * sms-client
 * API for sms-send functions
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/com.nvt.api.client/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/com.nvt.api.client/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.SmsClient);
  }
}(this, function(expect, SmsClient) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new SmsClient.SmsSendRequest();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('SmsSendRequest', function() {
    it('should create an instance of SmsSendRequest', function() {
      // uncomment below and update the code to test SmsSendRequest
      //var instane = new SmsClient.SmsSendRequest();
      //expect(instance).to.be.a(SmsClient.SmsSendRequest);
    });

    it('should have the property senderName (base name: "senderName")', function() {
      // uncomment below and update the code to test the property senderName
      //var instance = new SmsClient.SmsSendRequest();
      //expect(instance).to.be();
    });

    it('should have the property body (base name: "body")', function() {
      // uncomment below and update the code to test the property body
      //var instance = new SmsClient.SmsSendRequest();
      //expect(instance).to.be();
    });

    it('should have the property phone (base name: "phone")', function() {
      // uncomment below and update the code to test the property phone
      //var instance = new SmsClient.SmsSendRequest();
      //expect(instance).to.be();
    });

    it('should have the property source (base name: "source")', function() {
      // uncomment below and update the code to test the property source
      //var instance = new SmsClient.SmsSendRequest();
      //expect(instance).to.be();
    });

  });

}));
