/**
 * sms-client
 * API for sms-send functions
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import SmsSendRequest from '../com.nvt.api.client.model/SmsSendRequest';
import SmsSendResponse from '../com.nvt.api.client.model/SmsSendResponse';

/**
* Default service.
* @module com.nvt.api.client/com.nvt.api.client.api/DefaultApi
* @version 1.0.0
*/
export default class DefaultApi {

    /**
    * Constructs a new DefaultApi. 
    * @alias module:com.nvt.api.client/com.nvt.api.client.api/DefaultApi
    * @class
    * @param {module:com.nvt.api.client/ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:com.nvt.api.client/ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the smsSend operation.
     * @callback module:com.nvt.api.client/com.nvt.api.client.api/DefaultApi~smsSendCallback
     * @param {String} error Error message, if any.
     * @param {module:com.nvt.api.client/com.nvt.api.client.model/SmsSendResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Send a text message request.
     * @param {module:com.nvt.api.client/com.nvt.api.client.model/SmsSendRequest} smsSendRequest 
     * @param {module:com.nvt.api.client/com.nvt.api.client.api/DefaultApi~smsSendCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:com.nvt.api.client/com.nvt.api.client.model/SmsSendResponse}
     */
    smsSend(smsSendRequest, callback) {
      let postBody = smsSendRequest;
      // verify the required parameter 'smsSendRequest' is set
      if (smsSendRequest === undefined || smsSendRequest === null) {
        throw new Error("Missing the required parameter 'smsSendRequest' when calling smsSend");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['ApiKeyAuth'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = SmsSendResponse;
      return this.apiClient.callApi(
        '/sms/send', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
